# Generated by Django 4.0 on 2022-02-25 18:50

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gitUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=5000, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('g_id', models.PositiveIntegerField(blank=True, null=True)),
                ('node_id', models.CharField(max_length=5000, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('html_url', models.URLField(blank=True, null=True)),
                ('followers_url', models.URLField(blank=True, null=True)),
                ('following_url', models.URLField(blank=True, null=True)),
                ('repos_url', models.URLField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
                ('company', models.CharField(blank=True, max_length=2000, null=True)),
                ('blog', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=2000, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hireable', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, max_length=20000, null=True)),
                ('twitter_username', models.CharField(blank=True, max_length=2000, null=True)),
                ('public_repos', models.PositiveIntegerField(blank=True, null=True)),
                ('followers', models.PositiveIntegerField(blank=True, null=True)),
                ('following', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=1000)),
                ('url', models.URLField(null=True)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrendingRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.TextField(null=True)),
                ('pop_topics_list', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_id', models.PositiveIntegerField(null=True)),
                ('name', models.CharField(max_length=5000, null=True)),
                ('html_url', models.URLField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('languages_url', models.URLField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('size', models.PositiveIntegerField(null=True)),
                ('stargazers_count', models.PositiveIntegerField(null=True)),
                ('watchers_count', models.PositiveIntegerField(null=True)),
                ('forks_count', models.PositiveIntegerField(null=True)),
                ('language', models.CharField(max_length=5000, null=True)),
                ('all_languages', jsonfield.fields.JSONField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='git.gituser')),
                ('topics', models.ManyToManyField(null=True, related_name='repos_in_topic', to='git.Topic')),
            ],
        ),
    ]
