# Generated by Django 4.0 on 2022-02-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Paste token here', max_length=1000)),
                ('account', models.CharField(blank=True, help_text='Just for identification if needed', max_length=1000, null=True)),
            ],
        ),
    ]
