# Generated by Django 4.0 on 2022-02-25 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0002_gittoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GitToken',
        ),
    ]
