# Generated by Django 4.0 on 2022-02-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0004_gittoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gituser',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='repo',
            name='contributors',
            field=models.ManyToManyField(related_name='contributed_repos', to='git.gitUser'),
        ),
        migrations.AddField(
            model_name='repo',
            name='fork',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='repo',
            name='forked_from',
            field=models.ManyToManyField(related_name='forked_repos', to='git.gitUser'),
        ),
        migrations.AddField(
            model_name='repo',
            name='forkers',
            field=models.ManyToManyField(related_name='repos_forked', to='git.gitUser'),
        ),
        migrations.AddField(
            model_name='repo',
            name='stargazers',
            field=models.ManyToManyField(related_name='stargazed_repos', to='git.gitUser'),
        ),
        migrations.AddField(
            model_name='repo',
            name='url',
            field=models.URLField(default='h', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repo',
            name='watchers',
            field=models.ManyToManyField(related_name='repos_watched', to='git.gitUser'),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='repo',
            name='topics',
            field=models.ManyToManyField(related_name='repos_in_topic', to='git.Topic'),
        ),
        migrations.AlterField(
            model_name='trendingrepo',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
