# Generated by Django 4.0 on 2022-02-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0005_alter_gituser_options_repo_contributors_repo_fork_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gituser',
            name='has_details',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
